version: '2'

services:

    redis:
        image: redis:5-alpine
        ports:
            - 63790:6379
        volumes:
            - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
